server:
  port: 8085

spring:
  application:
    name: fmi-codes-proj-gateway
  cloud:
    gateway:
      routes:
        - id: UV-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/uv/**
        - id: USER-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/users/**
        - id: ML-SERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/ml/**
        - id: ADVISOR-SERVICE
          uri: http://localhost:9093
          predicates:
            - Path=/advice